project            = "demo"
instance_type      = "t2.micro"
ami_id             = "ami-0c55b159cbfafe1f0"   
db_instance_size   = "db.t3.micro"
db_username        = "devadmin"
db_password        = "ReplaceMe123!"          